### ISSUE TITLE
Publish artifact as package

### ISSUE THREAD

**Issue by mipastgt** [barbeau/earth-gravitational-model#8]
It would be nice if you could slightly extend your workflow and publish this artifact as a package so that people can directly use this as a dependency and don't have to build it themselves. This would significantly simplify other peoples workflows. See: https://github.com/features/packages

**Comment by barbeau** [comment]
@mipastgt Agreed! That's certainly my intent here, although I was still considering whether to package the model file directly in the library or allow it to be passed in by the application (e.g., to avoid increasing the initial download size of mobile apps). 

I suppose I could always just release a v1 as-is and iterate on that with a different design. FYI, I work on this project on my lunch breaks (along with others) so it may move slowly.

**Comment by Michael14K** [comment]
Hi @barbeau, I wanted to ask exactly the same question! It would be great if this could be added as a dependency. It would make it a lot easier for developers (including myself) to add it.
Thanks a lot for your work on this! I appreciate it so much. Cheers!

**Comment by mipastgt** [comment]
@barbeau For my own purposes I am currently using a fork of your project because of this. The only thing you would have to do is add the Gradle equivalent of this
```
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
```
to your workflow.
